require 'person'
require_relative 'decorator'
require_relative 'trimmer'
require_relative 'capitalize'
require_relative 'classroom'
require_relative 'student'
require_relative 'book'
require_relative 'rental'
